backend:
  name: gitlab
  branch: main
  repo: nicorio42/le-bouillon-restaurant
  auth_type: pkce
  app_id: de3bf42d6990ad57f4ab8346eabdfc1e0798ae1d4518b57e0d3e07adde713e95

locale: "fr"
media_folder: "src/assets"
public_folder: "@assets"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Page d'accueil"
        name: "index"
        file: "src/content/index-page/index.md"
        fields:
          - { label: Titre SEO, name: seoTitle, widget: string }
          - { label: Description SEO, name: seoDescription, widget: string }
          - { label: Titre, name: headline, widget: string }
          - { label: Contenu, name: body, widget: markdown }
