backend:
  name: gitlab
  branch: main
  repo: nicorio42/le-bouillon-restaurant
  auth_type: pkce
  app_id: de3bf42d6990ad57f4ab8346eabdfc1e0798ae1d4518b57e0d3e07adde713e95

locale: "fr"
media_folder: "src/assets"
public_folder: "@assets"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Page d'accueil"
        name: "index"
        file: "src/content/pages/index.json"
        fields:
          - { label: Titre, name: title, widget: string }
          - { label: Description, name: description, widget: string }
